### PR TITLE
Added mod2pi method

### PR DESCRIPTION
**Pull request by papamarkou**
This PR stems from issue #34, cc @fredo-dedup, @eford.

### CODE REVIEW

**Comment by fredo-dedup** [comment]
Thanks @scidom 

Could you also a test for this rule in `firstorder.jl` too ? such as : 
```julia
@compare mod2pi(x)    v0ref
```

Do you see other obvious functions that are missing too ? This could help making the PR more substantial and useful (if you are in a hurry, just tell me, and I'll push it as it is).

By quickly looking into julia standard mathematical functions, I find : 
- tan, sinh, cosh, tanh, asin, acos, atan
- round, floor, ceil, trunc
- expm1, lop1p
- erf, erfc, gamma, digamma, beta, lbeta, lgamma

Some of them could be useful for calculating derivatives of pdfs and cdfs of distributions.

**Comment by scidom** [comment]
Yes, @fredo-dedup, I can help with this since several of the functions you mentioned will be useful in the future. I am on my way to London today, but will be free to look at this from Friday once back.

@eford, are you happy to wait till we add the above extra functionality proposed by @fredo-dedup or you prefer that we merge the PR asap?

**Comment by eford** [comment]
Yes, I'm happy to wait till next week for a PR to be merged.

I'd likely even use some of those functions being added, particularly

   - tan, asin, acos, atan
   - round, floor, ceil
   - lop1p

I was afraid that auto diff might struggle with functions that
havediscontinuities.

Thanks

On Thu, Mar 31, 2016 at 4:31 AM, Theodore Papamarkou <
notifications@github.com> wrote:

> Yes, @fredo-dedup <https://github.com/fredo-dedup>, I can help with this
> since several of the functions you mentioned will be useful in the future.
> I am on my way to London today, but will be free to look at this from
> Friday once back.
>
> @eford <https://github.com/eford>, are you happy to wait till we add the
> above extra functionality proposed by @fredo-dedup
> <https://github.com/fredo-dedup> or you prefer that we merge the PR asap?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaDiff/ReverseDiffSource.jl/pull/35#issuecomment-203819132>
>



-- 
Eric Ford
Professor of Astronomy & Astrophysics
Center for Exoplanets & Habitable Worlds
Center for Astrostatistics
Institute for CyberScience
Penn State Astrobiology Research Center
Pennsylvania State University

**Comment by fredo-dedup** [comment]
`mod2pi`  and the above-mentionned functions were added with 0.2.3 => closing this PR

**Comment by scidom** [comment]
Thanks for doing this @fredo-dedup, looking forward to its metadata merge.

**Comment by scidom** [comment]
@fredo-dedup, thanks for your work and for adding the new functions. May I kindly ask if it would be possible to make the differentiation rule work with vector input, as they currently work only with scalar input?

**Comment by fredo-dedup** [comment]
`mod2pi`does not seem to be defined for Arrays in the first place so there is no point in defining the derivation rule, does it ?

**Comment by scidom** [comment]
Yes, you are right @fredo-dedup, let's wait to see then how things will work out with the merging of `mod2pi`, and then we can think again if anything needs to be done on the ReverseDiffSource side.

**Pull request closed without merging**
